apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-cd/manifests/cluster-install
- argocd-vault-replacer-secret.yml
- serviceaccount.yml

patchesStrategicMerge:
- argocd-repo-server-deploy.yaml
- argocd-cm.yaml

patches:
- path: argo-cm.yml
  target:
    kind: ConfigMap
    name: argocd-cm
- path: argocd-vault-replacer.yml
  target:
    kind: Deployment
    name: argocd-repo-server
- path: patch-serviceAccount.yml
  target:
    kind: Deployment
    name: argocd-repo-server
